eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/
server:
  port: 8888
spring:
  application:
    name: sc-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuyizyk/note
          search-paths: notes/springcloud-config-repo
          username: null
          password: null
      label: dev
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: test
    password: test123
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh